// Each: { city, stationLabel, icao, lat, lon, tz }
// tz is an IANA timezone, used to show each place's local time independently of
// the forecast API (so local time still works when the forecast is unavailable).
export const STATIONS = [
  { city: 'Seoul', stationLabel: 'Incheon Intl Airport', icao: 'RKSI', lat: 37.469, lon: 126.451, tz: 'Asia/Seoul' },
  { city: 'Houston', stationLabel: 'William P. Hobby Airport', icao: 'KHOU', lat: 29.645, lon: -95.279, tz: 'America/Chicago' },
  { city: 'Chicago', stationLabel: "O'Hare Intl Airport", icao: 'KORD', lat: 41.978, lon: -87.904, tz: 'America/Chicago' },
  { city: 'Warsaw', stationLabel: 'Warsaw Chopin Airport', icao: 'EPWA', lat: 52.166, lon: 20.967, tz: 'Europe/Warsaw' },
  { city: 'Austin', stationLabel: 'Austin-Bergstrom Intl', icao: 'KAUS', lat: 30.194, lon: -97.670, tz: 'America/Chicago' },
  { city: 'London', stationLabel: 'London City Airport', icao: 'EGLC', lat: 51.505, lon: 0.055, tz: 'Europe/London' },
  { city: 'Shanghai', stationLabel: 'Pudong Intl Airport', icao: 'ZSPD', lat: 31.143, lon: 121.805, tz: 'Asia/Shanghai' },
  { city: 'Paris', stationLabel: 'Paris-Le Bourget Airport', icao: 'LFPB', lat: 48.969, lon: 2.441, tz: 'Europe/Paris' },
  { city: 'Beijing', stationLabel: 'Capital Intl Airport', icao: 'ZBAA', lat: 40.080, lon: 116.585, tz: 'Asia/Shanghai' },
  { city: 'Munich', stationLabel: 'Munich Airport', icao: 'EDDM', lat: 48.354, lon: 11.786, tz: 'Europe/Berlin' },
  { city: 'NYC', stationLabel: 'LaGuardia Airport', icao: 'KLGA', lat: 40.777, lon: -73.872, tz: 'America/New_York' },
  { city: 'Denver', stationLabel: 'Buckley Space Force Base', icao: 'KBKF', lat: 39.717, lon: -104.752, tz: 'America/Denver' },
  { city: 'Mexico City', stationLabel: 'Benito Juárez Intl', icao: 'MMMX', lat: 19.436, lon: -99.072, tz: 'America/Mexico_City' },
  { city: 'Miami', stationLabel: 'Miami Intl Airport', icao: 'KMIA', lat: 25.793, lon: -80.290, tz: 'America/New_York' },
  { city: 'Singapore', stationLabel: 'Changi Airport', icao: 'WSSS', lat: 1.359, lon: 103.989, tz: 'Asia/Singapore' },
  { city: 'Tokyo', stationLabel: 'Haneda Airport', icao: 'RJTT', lat: 35.552, lon: 139.780, tz: 'Asia/Tokyo' },
  // WU/Polymarket resolve "Shenzhen ZGSZ" on the Lau Fau Shan (HK) station, NOT the
  // airport — so we forecast Lau Fau Shan's coords. No METAR there (not an airport),
  // so this row is forecast-only. Whole-°C region → reportsTenths:false.
  { city: 'Shenzhen', stationLabel: "Lau Fau Shan, HK (WU's 'Shenzhen')", icao: null, lat: 22.469, lon: 113.983, tz: 'Asia/Hong_Kong', reportsTenths: false, resolveNote: "WU/Polymarket resolve 'Shenzhen' on the Lau Fau Shan (Hong Kong) station, ~2° cooler than Bao'an airport. This row forecasts Lau Fau Shan — the value the market actually uses." },
  { city: 'Amsterdam', stationLabel: 'Schiphol Airport', icao: 'EHAM', lat: 52.309, lon: 4.764, tz: 'Europe/Amsterdam' },
  { city: 'Wellington', stationLabel: 'Wellington Intl Airport', icao: 'NZWN', lat: -41.327, lon: 174.805, tz: 'Pacific/Auckland' },
  { city: 'Madrid', stationLabel: 'Adolfo Suárez Barajas', icao: 'LEMD', lat: 40.472, lon: -3.561, tz: 'Europe/Madrid' },
  { city: 'Taipei', stationLabel: 'Songshan Airport', icao: 'RCSS', lat: 25.069, lon: 121.552, tz: 'Asia/Taipei' },
  { city: 'Lucknow', stationLabel: 'Chaudhary Charan Singh Intl', icao: 'VILK', lat: 26.761, lon: 80.889, tz: 'Asia/Kolkata' },
  { city: 'Milan', stationLabel: 'Malpensa Intl Airport', icao: 'LIMC', lat: 45.630, lon: 8.728, tz: 'Europe/Rome' },
  { city: 'Manila', stationLabel: 'Ninoy Aquino Intl', icao: 'RPLL', lat: 14.509, lon: 121.020, tz: 'Asia/Manila' },
  { city: 'Kuala Lumpur', stationLabel: 'KL Intl Airport', icao: 'WMKK', lat: 2.746, lon: 101.710, tz: 'Asia/Kuala_Lumpur' },
  { city: 'Jeddah', stationLabel: 'King Abdulaziz Intl', icao: 'OEJN', lat: 21.680, lon: 39.157, tz: 'Asia/Riyadh' },
  { city: 'Helsinki', stationLabel: 'Helsinki-Vantaa Airport', icao: 'EFHK', lat: 60.317, lon: 24.963, tz: 'Europe/Helsinki' },
  { city: 'Wuhan', stationLabel: 'Tianhe Intl Airport', icao: 'ZHHH', lat: 30.784, lon: 114.208, tz: 'Asia/Shanghai' },
  { city: 'Seattle', stationLabel: 'Seattle-Tacoma Intl', icao: 'KSEA', lat: 47.450, lon: -122.309, tz: 'America/Los_Angeles' },
  { city: 'Ankara', stationLabel: 'Esenboğa Intl Airport', icao: 'LTAC', lat: 40.128, lon: 32.995, tz: 'Europe/Istanbul' },
  { city: 'Atlanta', stationLabel: 'Hartsfield-Jackson Intl', icao: 'KATL', lat: 33.640, lon: -84.427, tz: 'America/New_York' },
  { city: 'Chengdu', stationLabel: 'Shuangliu Intl Airport', icao: 'ZUUU', lat: 30.578, lon: 103.947, tz: 'Asia/Shanghai' },
  { city: 'Chongqing', stationLabel: 'Jiangbei Intl Airport', icao: 'ZUCK', lat: 29.719, lon: 106.642, tz: 'Asia/Shanghai' },
  { city: 'Los Angeles', stationLabel: 'Los Angeles Intl', icao: 'KLAX', lat: 33.942, lon: -118.408, tz: 'America/Los_Angeles' },
  { city: 'Sao Paulo', stationLabel: 'Guarulhos Intl Airport', icao: 'SBGR', lat: -23.435, lon: -46.473, tz: 'America/Sao_Paulo' },
  { city: 'Busan', stationLabel: 'Gimhae Intl Airport', icao: 'RKPK', lat: 35.180, lon: 128.938, tz: 'Asia/Seoul' },
  { city: 'Istanbul', stationLabel: 'Istanbul Airport', icao: 'LTFM', lat: 41.262, lon: 28.742, tz: 'Europe/Istanbul', resolveNote: "Wunderground had no data under LTFM — verify which station its market uses before bidding." },
  { city: 'San Francisco', stationLabel: 'San Francisco Intl', icao: 'KSFO', lat: 37.619, lon: -122.375, tz: 'America/Los_Angeles' },
  { city: 'Moscow', stationLabel: 'Vnukovo Intl Airport', icao: 'UUWW', lat: 55.591, lon: 37.261, tz: 'Europe/Moscow' },
  { city: 'Tel Aviv', stationLabel: 'Ben Gurion Intl', icao: 'LLBG', lat: 32.011, lon: 34.887, tz: 'Asia/Jerusalem' },
  { city: 'Dallas', stationLabel: 'Dallas Love Field', icao: 'KDAL', lat: 32.847, lon: -96.852, tz: 'America/Chicago' },
  { city: 'Guangzhou', stationLabel: 'Baiyun Intl Airport', icao: 'ZGGG', lat: 23.392, lon: 113.299, tz: 'Asia/Shanghai' },
  { city: 'Panama City', stationLabel: 'Marcos A. Gelabert Intl', icao: 'MPMG', lat: 8.973, lon: -79.556, tz: 'America/Panama' },
  { city: 'Qingdao', stationLabel: 'Jiaodong Intl Airport', icao: 'ZSQD', lat: 36.366, lon: 120.086, tz: 'Asia/Shanghai' },
  { city: 'Cape Town', stationLabel: 'Cape Town Intl Airport', icao: 'FACT', lat: -33.969, lon: 18.597, tz: 'Africa/Johannesburg' },
]
